import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    container: {
        // backgroundColor: 'red',
        backgroundColor: 'black',
        height: '100%',
        width: '100%',
    },
    detailTipHeader: {
        flexDirection: 'row',
        marginTop: 8,
    },
    detailTipRightHeader: {
        flexDirection: 'row',
        marginLeft: 220,
    },
    detailTipName: {
        color: 'white',
        marginRight: 8,
    },
    detailTipConstPane: {
        flexDirection: 'row',
    },
    detailTipDateTimeLabel: {
        width: '100%',
        color: 'white',
        textAlign: 'center',
        fontSize: 15,
        marginTop: 12,
        marginBottom: 4,
    },
    detailTipTeamLabel: {
        width: '100%',
        textAlign: 'center',
        color: 'white',
        fontSize: 20,
        marginBottom: 32,
    },
    detailTipNavButtonPane: {
        marginTop: 12,
        marginBottom: 32,
        flexDirection: 'row',
        backgroundColor: 'grey',
        width: '80%',
        left: '8%',
        borderRadius: 28,
        flexDirection: 'row',
    },
    detailTipNavButton: {
        width: 192,
        borderWidth: 1,
        borderRadius: 28,
        borderColor: 'transparent',
        color: 'white',
        padding: 12,
    },
    detailTipNavActiveButton: {
        width: 192,
        borderWidth: 1,
        borderRadius: 28,
        borderColor: '#007a78',
        backgroundColor: '#007a78',
        color: 'white',
        padding: 12,
    },
    detailTipConstPane: {
        marginBottom: 24,
        flexDirection:'row',
    },
    detailTipoddPane: {
        flexDirection: 'row',
        backgroundColor: '#007a78',
        width: '40%',
        marginLeft: '7%',
        flexDirection:'row',
        borderRadius: 8,
    },
    detailTipoddLabel: {
        padding: 8,
        color: 'white',
        width: 100,
        fontSize: 16,
    },
    detailTipoddValue: {
        padding: 8,
        color: 'white',
        width: 88,
        textAlign: 'right',
        fontSize: 16,
    },
    detailTipReturnLabel: {
        left: '8%',
        width: '84%',
        borderWidth: 1,
        borderRadius: 12,
        borderColor: 'grey',
        textAlign: 'center',
        color: 'white',
        fontSize: 16,
        padding: 8,
    },
    detailTipContent: {
        left: '12%',
        width: '76%',
        marginTop: 20,
    },
    detailTipContentLabel: {
        color: 'white',
        fontSize: 14,
        marginBottom: 16,
    },
    bettingticketPane: {
        width: '100%',
        justifyContent: 'center',
        marginBottom: 20,
    },
    bettingticketImage: {
        left: 145
    },
    betButton: {
        color: 'white',
        backgroundColor: '#007a78',
        width: 120,
        left: 180,
        padding: 8,
        paddingLeft: 22,
        flexDirection: 'row',
    },
});